"""Change task model,add progress property

Revision ID: 7bd049a7acff
Revises: 21fcd605f393
Create Date: 2017-01-09 10:47:45.118753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd049a7acff'
down_revision = '21fcd605f393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fdm_machines',
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('x_size', sa.Integer(), nullable=True),
    sa.Column('y_size', sa.Integer(), nullable=True),
    sa.Column('z_size', sa.Integer(), nullable=True),
    sa.Column('material', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ip_address')
    )
    op.drop_table('FDM_machines')
    op.add_column('tasks', sa.Column('progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'progress')
    op.create_table('FDM_machines',
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=True),
    sa.Column('x_size', sa.INTEGER(), nullable=True),
    sa.Column('y_size', sa.INTEGER(), nullable=True),
    sa.Column('z_size', sa.INTEGER(), nullable=True),
    sa.Column('material', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('ip_address')
    )
    op.drop_table('fdm_machines')
    # ### end Alembic commands ###
