"""change task model

Revision ID: 90b5633da612
Revises: 5a71ca390284
Create Date: 2017-02-14 15:09:04.111935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b5633da612'
down_revision = '5a71ca390284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('file_name', sa.String(length=64), nullable=True))
    op.add_column('tasks', sa.Column('uuid', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_file_name'), 'tasks', ['file_name'], unique=True)
    op.drop_index('ix_tasks_name', table_name='tasks')
    op.drop_column('tasks', 'content')
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('tasks', sa.Column('content', sa.TEXT(), nullable=True))
    op.create_index('ix_tasks_name', 'tasks', ['name'], unique=1)
    op.drop_index(op.f('ix_tasks_file_name'), table_name='tasks')
    op.drop_column('tasks', 'uuid')
    op.drop_column('tasks', 'file_name')
    # ### end Alembic commands ###
